# Generated by Django 4.2.6 on 2023-11-26 14:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('base', '0002_citizenuser_staffuser_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='customuser',
            name='phone',
            field=models.IntegerField(default=None),
        ),
        migrations.AlterField(
            model_name='staffuser',
            name='staff_id',
            field=models.CharField(max_length=10, primary_key=True, serialize=False),
        ),
    ]
