# Generated by Django 4.2.6 on 2023-11-26 15:55

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('base', '0004_alter_customuser_phone'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='staffuser',
            name='staff_id',
        ),
        migrations.AlterField(
            model_name='staffuser',
            name='customuser_ptr',
            field=models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to=settings.AUTH_USER_MODEL),
        ),
    ]
