# Generated by Django 4.2.6 on 2023-11-27 18:03

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('base', '0005_remove_staffuser_staff_id_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='Survey',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('survey_id', models.IntegerField()),
                ('house_no', models.IntegerField()),
                ('house_name', models.CharField(max_length=50)),
                ('address', models.CharField(max_length=20)),
                ('survey_desc', models.TextField()),
                ('estimated_loss', models.DecimalField(decimal_places=2, max_digits=8)),
            ],
        ),
        migrations.CreateModel(
            name='Transfer',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=20)),
                ('phone_no', models.CharField(blank=True, max_length=10, unique=True)),
                ('account_no', models.IntegerField()),
                ('ifsc', models.CharField(max_length=11)),
                ('amount_sent', models.DecimalField(decimal_places=2, max_digits=8)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='base.citizenuser')),
            ],
        ),
        migrations.CreateModel(
            name='CitizenDetails',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('house_no', models.IntegerField()),
                ('house_name', models.CharField(max_length=50)),
                ('address', models.CharField(max_length=20)),
                ('aadhar_no', models.CharField(max_length=12)),
                ('ration_no', models.IntegerField()),
                ('account_no', models.IntegerField()),
                ('ifsc', models.CharField(max_length=11)),
                ('description', models.TextField()),
                ('survey_result', models.BooleanField(default=False)),
                ('username', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='citizen_username', to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
