# Generated by Django 4.2.7 on 2023-12-04 16:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('base', '0006_survey_transfer_citizendetails'),
    ]

    operations = [
        migrations.AlterField(
            model_name='citizendetails',
            name='username',
            field=models.CharField(default=None, max_length=50),
        ),
    ]
