# Generated by Django 4.2.7 on 2023-12-05 16:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('base', '0007_alter_citizendetails_username'),
    ]

    operations = [
        migrations.AddField(
            model_name='citizendetails',
            name='village_code',
            field=models.CharField(default=None, max_length=10),
        ),
        migrations.AddField(
            model_name='staffuser',
            name='village_code',
            field=models.CharField(default=None, max_length=10),
        ),
    ]
