# Generated by Django 4.2.7 on 2023-12-05 19:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('base', '0008_citizendetails_village_code_staffuser_village_code'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='survey',
            name='survey_id',
        ),
        migrations.AddField(
            model_name='survey',
            name='name',
            field=models.CharField(default=None, max_length=20),
            preserve_default=False,
        ),
    ]
