# Generated by Django 4.2.7 on 2023-12-05 19:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('base', '0009_remove_survey_survey_id_survey_name'),
    ]

    operations = [
        migrations.AddField(
            model_name='citizendetails',
            name='name',
            field=models.CharField(default=None, max_length=20),
            preserve_default=False,
        ),
    ]
