# Generated by Django 4.2.7 on 2023-12-06 05:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('base', '0010_citizendetails_name'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Survey',
        ),
        migrations.AlterField(
            model_name='citizendetails',
            name='username',
            field=models.CharField(max_length=50),
        ),
    ]
