# Generated by Django 4.2.7 on 2023-12-06 05:11

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('base', '0012_remove_citizendetails_id_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='Survey',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=20)),
                ('house_no', models.IntegerField()),
                ('house_name', models.CharField(max_length=50)),
                ('address', models.CharField(max_length=20)),
                ('survey_desc', models.TextField()),
                ('estimated_loss', models.DecimalField(decimal_places=2, max_digits=8)),
                ('username', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='base.citizendetails')),
            ],
        ),
    ]
